"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Image as ImageIcon, Sparkles, BookOpen, Brush } from "lucide-react";

export function InteractiveProductShowcase() {
  const [hoveredModule, setHoveredModule] = useState<string | null>(null);

  const outputs = [
    {
      id: 1,
      name: "Mandala Coloring Page",
      module: "Publishing Studio™",
      icon: BookOpen,
      visualType: "interior",
      imageSrc: "/images/mandala.png",
      colSpan: "col-span-1 md:col-span-2 row-span-2"
    },
    {
      id: 2,
      name: "Vector Book Cover",
      module: "Cover Studio™",
      icon: Brush,
      visualType: "cover",
      imageSrc: "/images/cover.png",
      colSpan: "col-span-1 md:col-span-2 row-span-2"
    },
    {
      id: 3,
      name: "Cryptogram Puzzle",
      module: "Publishing Studio™",
      icon: BookOpen,
      visualType: "puzzle",
      imageSrc: "/images/puzzle.png",
      colSpan: "col-span-1 md:col-span-2"
    },
    {
      id: 4,
      name: "Shadow Work Journal Layout",
      module: "Publishing Studio™",
      icon: BookOpen,
      visualType: "journal",
      imageSrc: "/images/journal.png",
      colSpan: "col-span-1 md:col-span-2"
    }
  ];

  return (
    <section className="py-24 sm:py-32 bg-black relative border-b border-white/5 overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        <div className="text-center max-w-3xl mx-auto mb-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 text-gray-300 font-semibold mb-6 text-sm uppercase tracking-widest"
          >
            <Sparkles className="w-4 h-4 text-primary-500" />
            Ecosystem Outputs
          </motion.div>

          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-3xl sm:text-5xl font-black text-white mb-6 tracking-tight"
          >
            Real Deliverables. <br />
            <span className="text-gray-500">Rendered In Real-Time.</span>
          </motion.h2>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2 }}
            className="text-lg text-gray-400 font-medium leading-relaxed"
          >
            Every output below is generated directly by the KDP Mafia Operating System. Hover over any asset to see exactly which module built it.
          </motion.p>
        </div>

        {/* The Interactive Gallery */}
        <div className="max-w-5xl mx-auto mt-12 relative">
          
          {/* Top UI Bar showing Active Module */}
          <div className="flex justify-center mb-8 h-10">
            <AnimatePresence mode="wait">
              {hoveredModule ? (
                <motion.div
                  key="active"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="bg-primary-500/20 border border-primary-500/40 text-primary-400 font-bold px-6 py-2 rounded-full shadow-[0_0_20px_rgba(255,138,0,0.2)] flex items-center gap-2"
                >
                  <span className="w-2 h-2 rounded-full bg-primary-500 animate-pulse" />
                  Generated by {hoveredModule}
                </motion.div>
              ) : (
                <motion.div
                  key="idle"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="text-gray-600 font-medium px-6 py-2"
                >
                  Hover over an asset...
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Masonry Grid */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 auto-rows-[150px]">
            {outputs.map((item) => (
              <motion.div
                key={item.id}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                onMouseEnter={() => setHoveredModule(item.module)}
                onMouseLeave={() => setHoveredModule(null)}
                className={`relative rounded-xl border border-white/10 overflow-hidden group cursor-crosshair transition-colors ${
                  hoveredModule === item.module ? 'border-primary-500/50' : 'hover:border-white/20'
                } ${item.colSpan}`}
              >
                {/* Visual Representation Background */}
                <div className={`absolute inset-0 transition-opacity duration-500 bg-[#0a0a0a] ${
                  hoveredModule && hoveredModule !== item.module ? 'opacity-30' : 'opacity-100'
                }`}>
                  <img 
                    src={item.imageSrc} 
                    alt={item.name} 
                    className="w-full h-full object-cover opacity-60 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700" 
                  />
                  {/* Dark overlay for readability */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black via-black/50 to-transparent" />
                </div>

                {/* Info Overlay */}
                <div className="absolute inset-x-0 bottom-0 p-4 bg-gradient-to-t from-black via-black/80 to-transparent flex items-end justify-between">
                  <div>
                    <h3 className="text-white font-bold text-sm">{item.name}</h3>
                    <p className={`text-xs mt-1 transition-colors ${hoveredModule === item.module ? 'text-primary-400' : 'text-gray-500'}`}>
                      {item.module}
                    </p>
                  </div>
                  <item.icon className={`w-5 h-5 transition-colors ${hoveredModule === item.module ? 'text-primary-500' : 'text-gray-600'}`} />
                </div>
                
                {/* Scanner effect on hover */}
                {hoveredModule === item.module && (
                  <div className="absolute inset-0 bg-primary-500/10" />
                )}
              </motion.div>
            ))}
          </div>

        </div>
      </div>
    </section>
  );
}
